# author mjaglan@umail.iu.edu
# Coding Style: Shell form

# Start from Official Node.js image
# specify the node base image with your desired version node:<version>
FROM node:6

# Create PROJECT directory
RUN mkdir /tmp/app/

# Set Project HOME
ENV PROJECT=/tmp/app/

# Set active working directory
WORKDIR $PROJECT

# Start process
ENTRYPOINT bash
